### ISSUE TITLE
Unflyable. After take-off, quickly diverges in pitch

### ISSUE THREAD

**Issue by jan-hudec** [FGMEMBERS/PC-9M#1]
The updated FDM from https://github.com/FGMEMBERS/PC-9M/commit/544c7c0e3bb0c84f35c2e62077973ec67ff0fce7 is broken. Take-off roll and rotation appears normal, but then the pitch starts to diverge and develops massive, fast, diverging phugoid oscillation that is almost impossible to manage and impossible to manage in any sort of realistic way.

The problem appears to be the changes in the `PITCH` axis. The static stability parameter, `aero/coefficient/Cmalpha` was reduced too much. When I increase it from `0.2511` to the previous value of `0.5`, the phugoid oscillation slows down to a manageable rate. It is still very pronounced though, because the `Cmq` and `Cmadot` that damp it were also reduced a lot, but I don't know how damped it should be in the real aircraft.

**Comment by JWocky** [comment]
I had only a short look, but can it be, you have pitch due to alpha anyway double implemented? The other thing is, the pressure point and the CoG are 5 inches different, which is not that much but if she has a tendecy to pitch up maybe because the CoG is still too far forward, this would amplify the effect.

**Comment by jan-hudec** [comment]
@JWocky,

> you have pitch due to alpha anyway double implemented?

I just quickly test it, but didn't commit it anywhere, because I don't want to just pull numbers out of thin air and I don't have any reference for how the plane should actually behave.

> The other thing is, the pressure point and the CoG are 5 inches different, which is not that much but if she has a tendecy to pitch up maybe because the CoG is still too far forward, this would amplify the effect.

Which pressure point? I believe JSBSim works with just moments around CoG and I don't see it mentioned in the model. Do you mean the input to aeromatic++ from which the `Cmalpha` was calculated? I don't see that anywhere either.

In either case, moving CoG _forward increases_ stability. So if anything, the centre of **pressure** is too far forward.

**Comment by JWocky** [comment]
Look at 
        <location name="AERORP" unit="IN">
            <x>  734 </x> 
            <y>    0 </y>
            <z>-6.71 </z> 
        </location>
(example is from another plane). Normally the further AERORP and CG are away from each other (with CG at or slightly the same), the more pitch problems will show up.

**Comment by jan-hudec** [comment]
@JWocky, ah, I see. However, that value did _not change_ between the good revision (FG2016.1, https://github.com/FGMEMBERS/PC-9M/commit/5ce4e0f28247c6e8f20cb4040c826050aa5656f2) and the bad revision (master, https://github.com/FGMEMBERS/PC-9M/commit/eaade9c64946a53bf509d77df2438806410fd2b9).

The AERORP is just a reference point. Any model can be expresses with any AERORP. The actual forces may have different action points, which is reflected in the moments. The simulation will work with CG only anyway, adding appropriate moments to convert it.

Of course since Aeromatic (either the web or the C++ version) pulls the moments out of a hat, they will only make sense if the AERORP is specified in the way Aeromatic expects it to be (and I don't really know where that is).

**Comment by FGDATA** [comment]
Thanks for noticing this @jan-hudec 

I am trying to revert to a correct FDM, but I dont know where to target.

Which one is the last version with **correct** FDM?

https://github.com/FGMEMBERS/PC-9M/commit/eaade9c64946a53bf509d77df2438806410fd2b9

https://github.com/FGMEMBERS/PC-9M/commit/544c7c0e3bb0c84f35c2e62077973ec67ff0fce7

https://github.com/FGMEMBERS/PC-9M/commit/5ce4e0f28247c6e8f20cb4040c826050aa5656f2

?

IH-COL

**Comment by FGDATA** [comment]
I think 5ce4e0f is the best one. I feel we shall revert the wrong FDM 
Do you agree? I can do that easy

**Comment by CA1012** [comment]
I will test fly the aircraft and give you my feedback as well. two sources
are better than one after all.

**Comment by FGDATA** [comment]
try those 3 versions

**Comment by jan-hudec** [comment]
> https://github.com/FGMEMBERS/PC-9M/commit/eaade9c64946a53bf509d77df2438806410fd2b9

This is the unusable one.

> https://github.com/FGMEMBERS/PC-9M/commit/544c7c0e3bb0c84f35c2e62077973ec67ff0fce7

This is the one where the unusable model was introduced. There is no change in FDM between this and https://github.com/FGMEMBERS/PC-9M/commit/eaade9c64946a53bf509d77df2438806410fd2b9

> https://github.com/FGMEMBERS/PC-9M/commit/5ce4e0f28247c6e8f20cb4040c826050aa5656f2

This is the last usable one.

**Comment by FGDATA** [comment]
@jan-hudec 
I reverted the conflicting commit

https://github.com/FGMEMBERS/PC-9M/commit/bc2a1e69f3c4dcf8a9d1b5aab8be77f5285c9a6f

Would you mind pulling the master branch and verifying the aircraft is back to the air with safety, now?

**Comment by CA1012** [comment]
I am at school right now but I can do the check at around 17:30 PST.

**Comment by FGDATA** [comment]
take your time. (and get off FG while on school :P)

Thanks, Orca!

**Comment by CA1012** [comment]
I don't have a PC. I'm on my phone! 😜

**Comment by jan-hudec** [comment]
Stable and controllable.

Still, I can't help but wonder how stuff like this gets committed in fgdata. This is not like breaking some obscure feature of autopilot or something but rather problem apparent in a trivial 10 second test.

**Comment by IAHM-COL** [comment]
I cant tell, but thanks for reporting and help us fixing this.
IH-COL

**Comment by FGDATA** [comment]
@jan-hudec 

Hi Jan

Erick had a second attempt at updating the aircraft on FGADDon
b2456d0cd9a19c7cee344c9c0b9e84043feb4424

I accepted his FGAddon changes again. It seems to me this attempt is a more serious one. (as in probably improving of the plane)

I reopen the issue, on the doubt that this has been properly tested, and I was hoping you wouldn't mind giving the master branch HEAD another flying and evaluate.

I will consider this issue closed per your report, and thanks

Thanks
@IAHM-COL

**Comment by jan-hudec** [comment]
Yes, this model looks good. I see two small problems:
- It might have a bit excessive wing camber though; the plane flies at significant negative pitch at 180 KIAS already.
- The added engine and propeller files don't seem to be actually used. They are new files, but I didn't seem to notice the name of the engine was changed. But maybe I just missed it.

I am also getting a crash upon gear retraction since I last updated flightgear, but that is unrelated to this issue. It seems to be something with sound having pitch, but not volume specified.

**Comment by FGDATA** [comment]
Hi @jan-hudec 
For the revision of these later commits, and for the gear retraction crash fixes.

Best
@IAHM-COL
